### ISSUE TITLE
Determining homozygous or heterozygous genotype from predictions

### ISSUE THREAD

**Issue by sa256** [bcgsc/HLAminer#10]
Hello,

I ran HLAminer on RNAseq data and got some predictions for different HLAs. As per manual, predictions 1 and 2 represent two different alleles. I have few questions regarding this:

1) If there is no prediction 2, does it mean the sample is homozygous for that HLA gene?
example if prediction 1 is A*24:02 and no. prediction2, then the genotype for the individual will be: A*24:02+A*24:02 ?

2) For one of my sample, there were two prediction 1 and no prediction 2 for HLA-A gene. Snapshot of the results is as follows:

```
HLA-A |   |   |  
-- | -- | -- | --
Prediction #1 - A*24 |   |  
A*24:02P | 3087080 | 5.58E-06 | 52.5
A*24:225P | 3087080 | 5.58E-06 | 52.5
A*24:07P | 3087080 | 5.58E-06 | 52.5
A*24:135P | 3087080 | 5.58E-06 | 52.5
A*24:20P | 3087080 | 5.58E-06 | 52.5
A*24:142P | 3087080 | 5.58E-06 | 52.5
A*24:14P | 3087080 | 5.58E-06 | 52.5
A*24:26P | 3087080 | 5.58E-06 | 52.5
Prediction #1 - A*02 (same score as above)
A*02:19 | 3087080 | 5.58E-06 | 52.5
```
 In this case, I understand that A*24 prediction is not very reliable as it has multiple alleles predicted. And a better choice will be A*02. My question: is there a possibility that A*24 and A*02 could be two different alleles? Why are different allele groups called as prediction 1 instead of two different predictions?

3) In case of A*24:02, if I try to fetch the protein sequence for this allele, I get multiple entries from IGMT like:

```
>HLA:HLA00050 A*24:02:01:01 365 bp
>HLA:HLA00051 A*24:02:01:02L 365 bp
>HLA:HLA06112 A*24:02:01:03 365 bp
>HLA:HLA13780 A*24:02:01:04 365 bp
>HLA:HLA13786 A*24:02:01:05 365 bp
```
 and many more. Which sequence should I go for in these kind of cases?

Thanks

**Comment by warrenlr** [comment]
thank you for your comment and interest in HLAminer.

(1) HLAminer does not impute zigosity.  It could be, for whatever reason (eg. low coverage, reference HLA unknown, score below threshold), that a second prediction was not possible. I'd refrain from the temptation to infer zygosity based on lack of info reported..it is a possibility, but definitely not a certainty.

(2) This happens when the score is the same.  The score is calculated based on base-level evidence and derived from pair-wise alignments.  Same score indicate that there's not enough discriminatory power to reveal the most likely allele.

(3) I designed HLAminer to ultimately* report up to 2 groups (allele group:specific hla protein), and use the P-designation when multiple entries exist/match, to simplify the reports. In many cases, there's not enough coverage/sequencing information to categorically assign an HLA. In case of RNAseq, you would never be able to decipher the 4th group since the nomenclature reports difference in non-coding regions. It may be possible to report the 3rd group, as the naming is used to report on synonymous substitution within the coding region.  Please refer to: http://hla.alleles.org/nomenclature/naming.html

*Although HLAminer reports its predictions in a .csv, raw predictions that show more granularity are available from the corresponding .log file.  

Hope this helps!
