### ISSUE TITLE
About haplotype of HLA

### ISSUE THREAD

**Issue by kwanghoon821** [bcgsc/HLAminer#14]
Hi

I used HLAminer for HLAtyping.

I'm curious that how do I know HLA haplotype of samples?

Thank you

**Comment by warrenlr** [comment]
As you know, HLAminer doesn't output the specific alleles or zygosity for its predictions. HLA alleles are simply ranked in most to least likely given the sequence support. That said, predictions could be used to infer putative haplotypes, alleles with higher probability of co-occurrence. These haplotypes, however, aren't phased since the allelic contribution isn't known.  I hope this helps.

thank you for your interest in HLAminer
