### ISSUE TITLE
Illegal division by zero at HLAminer_v1.3.1/bin//HLAminer.pl line 362.

### ISSUE THREAD

**Issue by vinegang** [bcgsc/HLAminer#25]
Hi, I am analyzing RNA samples and several of them have errrored out with the following error. Could you help me understand this. Is this because the output is empty?

Thanks!

```
sh /HLAminer_v1.3.1/bin/HPTASRwgs_classI.sh /HLAminer_v1.3.1/bin/ output/Sample_212_T/HLA/HLAminer/
[+] Loading perl 5.24 
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
[blastall] WARNING:  Database is empty
Illegal division by zero at /data/Clinomics/apps/HLAminer_v1.3.1/bin//HLAminer.pl line 362
```

**Comment by warrenlr** [comment]
some of your RNA samples completed successfully?  If so, maybe you could compare the output of the pipeline, side by side and see what is different?  I am inclined to say that this may be caused by absence of contigs -- but hard to say from this limited output.  Did you try the demo, and did it run successfully?

note: If you are working with RNA-Seq, I would recommend that you run  HPTASRrnaseq_classI.sh instead. Also make sure that the blast database is uptodate in the ./Database folder run the updateAll.sh script as per the readme.

**Comment by vinegang** [comment]
You are right. I noticed that for some samples,we did not have any contigs >200bp length. Hence the error.
